language = "python3"
function = "Solution().twoSum"

[[tests]]
arguments = { nums = [2,7,11,15], target = 9 }
expected = [0, 1]

[[tests]]
arguments = { nums = [3,2,4], target = 6 }
expected = [1, 2]

[[tests]]
arguments = { nums = [3,3], target = 6 }
expected = [0, 1]
