language = "python3"
function = "Solution().isValid"

[[tests]]
arguments = { "s" = "()" }
expected = true

[[tests]]
arguments = { "s" = "()[]{}" }
expected = true

[[tests]]
arguments = { "s" = "(]" }
expected = false

[[tests]]
arguments = { "s" = "([)]" }
expected = false

[[tests]]
arguments = { "s" = "{[]}" }
expected = true

