language = "python3"
[[tests]]
expected = 6
explanation = "The above elevation map (black section) is represented by array [0,1,0,2,1,0,1,3,2,1,2,1]. In this case, 6 units of rain water (blue section) are being trapped."

[tests.arguments]
height = [ 4, 2, 0, 3, 2, 5,]
[[tests]]
expected = 6
explanation = "The above elevation map (black section) is represented by array [0,1,0,2,1,0,1,3,2,1,2,1]. In this case, 6 units of rain water (blue section) are being trapped."


[tests.arguments]
height = [ 4, 2, 0, 3, 2, 5,]
[[tests]]
expected = 6
explanation = "The above elevation map (black section) is represented by array [0,1,0,2,1,0,1,3,2,1,2,1]. In this case, 6 units of rain water (blue section) are being trapped."


[tests.arguments]
height = [ 4, 2, 0, 3, 2, 5,]
[[tests]]
expected = 6
explanation = "The above elevation map (black section) is represented by array [0,1,0,2,1,0,1,3,2,1,2,1]. In this case, 6 units of rain water (blue section) are being trapped."


[tests.arguments]
height = [ 4, 2, 0, 3, 2, 5,]
[[tests]]
expected = 6
explanation = "The above elevation map (black section) is represented by array [0,1,0,2,1,0,1,3,2,1,2,1]. In this case, 6 units of rain water (blue section) are being trapped."


[tests.arguments]
height = [ 4, 2, 0, 3, 2, 5,]
[[tests]]
expected = 6
explanation = "The above elevation map (black section) is represented by array [0,1,0,2,1,0,1,3,2,1,2,1]. In this case, 6 units of rain water (blue section) are being trapped."

[tests.arguments]
height = [ 0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1,]
[[tests]]
expected = 9

[tests.arguments]
height = [ 0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1,]
[[tests]]
expected = 9

[tests.arguments]
height = [ 4, 2, 0, 3, 2, 5,]
[[tests]]
expected = 6
explanation = "The above elevation map (black section) is represented by array [0,1,0,2,1,0,1,3,2,1,2,1]. In this case, 6 units of rain water (blue section) are being trapped."

[tests.arguments]
height = [ 0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1,]
[[tests]]
expected = 9

[tests.arguments]
height = [ 4, 2, 0, 3, 2, 5,]

[function]
"*" = "trap"
python3 = "Solution().trap"
